services:
  gen:
    image: selfie-postcard-gen-gpu:latest
    build:
      context: ./gen
      dockerfile: Dockerfile.gpu
    ports:
      - "8081:8081"
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      TORCHVISION_DISABLE_NMS_EXPORT: "1"   # ключевая строка
      USE_CPU: "0"
      INPAINT_REPO: "runwayml/stable-diffusion-inpainting"
      TORCH_dtype: "fp16"
      MAX_SIDE: "1280"
      STEPS: "20"
      GUIDANCE: "5.0"
      STRENGTH: "0.5"
      OUTPUT_FORMAT: "png"

      DISABLE_HANDS: "0"
      DISABLE_FACEMESH: "0"
      SWAP_MODE: "after"
      DISABLE_FACE_SWAP: "0"
      INSIGHTFACE_DET_SIZE: "1000"
      FACE_MODEL_PATH: "/models/inswapper_128.onnx"

    volumes:
      - ./gen/models:/models:ro
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    restart: unless-stopped

volumes:
  hf_cache:
