version: "3.9"

services:
  gen:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: postcard-gen:gpu
    runtime: nvidia
    ports:
      - "8081:8081"
    volumes:
      - ./gen/models:/models:ro
      - hf_cache:/root/.cache/huggingface
    environment:
      # базовые
      PYTHONUNBUFFERED: "1"
      HF_HUB_ENABLE_HF_TRANSFER: "0"
      TRANSFORMERS_NO_TORCHVISION: "1"
      TOKENIZERS_PARALLELISM: "false"
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:128"
      TORCH_THREADS: "4"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"

      # модель и режимы
      INPAINT_REPO: "runwayml/stable-diffusion-inpainting"
      USE_CPU: "0"
      SKIP_INPAINT: "0"
      FALLBACK_INPAINT: ""
      MAX_SIDE: "1280"

      # SD-параметры
      STEPS: "18"
      GUIDANCE: "4.5"
      STRENGTH: "0.48"

      # кроп-инпейнт
      INPAINT_LONG: "1024"
      INPAINT_PAD_PCT: "0.06"
      MASK_GROW: "3"

      # край/альфа/контакт
      RING_IN_PCT: "0.004"
      RING_OUT_PCT: "0.012"
      SEAMLESS_EDGE: "1"
      EDGE_SNAP_ITERS: "1"   # <-- была опечатка

      # визуальные мелочи
      RIM_SHADE: "0.06"
      FINGER_DETAIL_GAIN: "0.35"
      FINGER_DETAIL_SIGMA: "1.1"
      GRAIN_STRENGTH: "0.012"

      # эффекты страницы
      PAGE_EFFECT: "1"
      PAGE_SIDE: "right"
      PAGE_INNER_PX: "16"
      PAGE_SHADE: "0.06"
      PAGE_STRIPES: "1"

      # FaceSwap
      DISABLE_FACE_SWAP: "0"
      SWAP_MODE: "before"
      INSIGHTFACE_DET_SIZE: "640"
      FACE_MODEL_PATH: "/models/inswapper_128.onnx"
      DISABLE_HANDS: "0"
      DISABLE_FACEMESH: "0"

    command: >
      uvicorn server:app --host 0.0.0.0 --port 8081
      --log-level info --access-log
      --timeout-keep-alive 120 --timeout-graceful-shutdown 120
    restart: unless-stopped

volumes:
  hf_cache:
