# Compose V2 (без поля version)
services:
  gen:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: postcard-selfie-gen:gpu
    ports:
      - "8081:8081"
    # требуется Docker с nvidia-container-toolkit
    deploy: {}
    gpus: all
    environment:
      PYTHONUNBUFFERED: "1"

      # Torch/threads
      TORCH_THREADS: "4"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      TOKENIZERS_PARALLELISM: "false"
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:128"
      TRANSFORMERS_NO_TORCHVISION: "1"
      HF_HUB_ENABLE_HF_TRANSFER: "0"

      # SD / Inpaint
      INPAINT_REPO: "runwayml/stable-diffusion-inpainting"
      TORCH_dtype: "fp16"
      MAX_SIDE: "1600"
      STEPS: "22"
      GUIDANCE: "4.0"
      STRENGTH: "0.46"

      # Патч-инпейнт
      INPAINT_LONG: "1400"
      INPAINT_PAD_PCT: "0.08"
      MASK_GROW: "4"

      # Кромка/контакт
      RING_IN_PCT: "0.0035"
      RING_OUT_PCT: "0.010"
      EDGE_SNAP_ITERS: "2"
      RIM_SHADE: "0.045"
      SEAMLESS_EDGE: "1"

      # Детали кожи/зерно
      FINGER_DETAIL_SIGMA: "1.1"
      FINGER_DETAIL_GAIN: "0.38"
      GRAIN_STRENGTH: "0.010"

      # Эффект страницы
      PAGE_EFFECT: "1"
      PAGE_SIDE: "right"
      PAGE_INNER_PX: "14"
      PAGE_SHADE: "0.05"
      PAGE_STRIPES: "1"

      # Faceswap
      DISABLE_FACE_SWAP: "0"
      SWAP_MODE: "after"
      SWAP_ENFORCE_FINAL: "1"
      INSIGHTFACE_DET_SIZE: "640"     # ретина лучше ловит source на меньшем разрешении
      INSIGHTFACE_DET_THRESH: "0.25"  # чуть выше, чтобы не ловить шум
      SWAP_EAR_EXPAND_PX: "36"        # шире зона ушей
      SWAP_EAR_MULT: "1.8"            # доп. множитель расширения по X
      SWAP_EAR_ITERS: "3"             # итерации ушного расширения
      SWAP_EAR_RECT_W: "24"           # ширина прямоугольных карманов уха
      SWAP_HAIR_EXPAND_PX: "20"       # зона над ушами
      SWAP_CHIN_CUT_PX: "2"           # низ почти не режем
      POISSON_FACE: "1"
      SWAP_POISSON_FULL: "1"          # полноразмерный Poisson, чтобы «переносить» уши/волосы
      SWAP_SHARP_GAIN: "0.28"
      FACE_MODEL_PATH: "/models/inswapper_128.onnx"
      DISABLE_HANDS: "0"
      DISABLE_FACEMESH: "0"
      SWAP_KEEP_EARS: "1"
      SWAP_CORE_SHRINK_PX: "8"
      # волосы источника (опционально)
      HAIR_FROM_SRC: "1"
      SWAP_FORCE_EARS: "1"
      SWAP_EAR_HARD: "1"
      SWAP_EAR_FEATHER: "6"
      SWAP_EAR_CLONE: "1"
      SWAP_EAR_CLONE_MODE: "normal"
      SWAP_EAR_ERODE: "1"
      SWAP_EAR_MIN_AREA: "500"
      HAIR_ALPHA: "0.3"
      SWAP_FORCE_FULL: "0"

      # Отладка
      SAVE_DEBUG: "0"
      SKIP_INPAINT: "0"
      FALLBACK_INPAINT: "0"
      OUTPUT_FORMAT: "png"
      USE_CPU: "0"

      SWAP_SELECT: "index"       # варианты: center | largest | index
      SWAP_INDEX: "1"             # используется, если SWAP_SELECT=index

      # усиление заметности свопа
      SWAP_CORE_GAIN: "1.5"      # 1.0..1.5 — сильнее «ядро» лица
      SWAP_HAIR_ALPHA: "1"     # 0..1    — слабее волосы (меньше артефактов по линии волос)
      SWAP_CORE_DILATE: "8"      # шире ядро

      # отладка
      SWAP_DEBUG: "1"
      DEFAULT_PROMPT: >-
        photorealistic selfie; person holding a postcard; keep postcard unchanged;
        natural skin texture; soft contact shadows; realistic fingers, no blur
      NEG_PROMPT: >-
        altered postcard, changed text, hdr halos, glow edges, extra fingers,
        deformed hands, warped text, logo distortion, oversharpen, blur, artifacts

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

    volumes:
      - ./gen/models:/models:ro
      - hf_cache:/root/.cache/huggingface
      - /tmp:/tmp

    restart: unless-stopped

volumes:
  hf_cache:
