# Compose V2 (без поля version)
services:
  gen:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: postcard-selfie-gen:gpu
    ports:
      - "8081:8081"
    # требуется Docker с nvidia-container-toolkit
    deploy: {}
    gpus: all
    environment:
      PYTHONUNBUFFERED: "1"

      # Torch/threads
      TORCH_THREADS: "4"                # кол-во потоков PyTorch (gen/pipeline.py)
      OMP_NUM_THREADS: "1"              # OpenMP threads (глобально)
      OPENBLAS_NUM_THREADS: "1"         # OpenBLAS threads (глобально)
      MKL_NUM_THREADS: "1"              # MKL threads (глобально)
      TOKENIZERS_PARALLELISM: "false"   # HuggingFace tokenizers (глобально)
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:128" # поведение CUDA‑аллокатора
      TRANSFORMERS_NO_TORCHVISION: "1"  # не тянуть torchvision (глобально)
      HF_HUB_ENABLE_HF_TRANSFER: "0"    # отключить hf_transfer (глобально)

      # SD / Inpaint
      INPAINT_REPO: "runwayml/stable-diffusion-inpainting"  # какой SD inpaint (gen/services/inpainter.py)
      TORCH_dtype: "fp16"            # fp16/fp32/CPU логика в Inpainter (gen/services/inpainter.py)
      MAX_SIDE: "1600"               # ограничение размера входов (gen/pipeline.py)
      STEPS: "32"                     # num_inference_steps (gen/services/inpainter.py)
      GUIDANCE: "6.0"                 # guidance_scale (gen/services/inpainter.py)
      STRENGTH: "0.66"               # denoise strength (gen/services/inpainter.py)

      # Патч-инпейнт
      INPAINT_LONG: "1400"            # длинная сторона патча для SD (gen/pipeline.py)
      INPAINT_PAD_PCT: "0.08"         # паддинг вокруг bbox (gen/pipeline.py)
      MASK_GROW: "4"                   # расширение маски для SD (gen/pipeline.py)

      # Кромка/контакт
      RING_IN_PCT: "0.0040"           # внутренний перо‑радиус для Laplacian blend (gen/utils/utils.py: ring_grad)
      RING_OUT_PCT: "0.012"            # внешний перо‑радиус (gen/utils/utils.py)
      EDGE_SNAP_ITERS: "3"             # уточнение альфы по краям (gen/utils/utils.py: refine_alpha_with_edges)
      RIM_SHADE: "0.06"                # затемнение у кромки (gen/pipeline.py)
      SEAMLESS_EDGE: "0"               # отключим Poisson по кромке — меньше мутности
      CARD_HARD_EDGE: "1"              # жёсткая кромка карточки без мутной маски (gen/pipeline.py)
      EDGE_BLEND_LEVELS: "3"           # уровни Laplacian‑blend, если CARD_HARD_EDGE=0 (gen/pipeline.py)
      DESPILL_GAIN: "0.85"             # прижать зелёный по кромке (gen/pipeline.py)

      # Детали кожи/зерно
      FINGER_DETAIL_SIGMA: "1.1"       # детализация кожи (gen/utils/utils.py: texture_reinject)
      FINGER_DETAIL_GAIN: "0.32"       # чуть мягче микротекстуры
      GRAIN_STRENGTH: "0.010"          # плёночное зерно (gen/utils/utils.py: add_fine_grain)

      # Эффект страницы
      PAGE_EFFECT: "1"                 # включить эффект страницы (gen/utils/utils.py: apply_page_stack)
      PAGE_SIDE: "right"               # сторона корешка (apply_page_stack)
      PAGE_INNER_PX: "14"              # ширина внутренней тени (apply_page_stack)
      PAGE_SHADE: "0.05"               # сила тени (apply_page_stack)
      PAGE_STRIPES: "1"                # полосы у корешка (apply_page_stack)

      # Faceswap
      DISABLE_FACE_SWAP: "0"           # полностью отключить своп (gen/pipeline.py)
      SWAP_MODE: "after"               # before/after относит. компоновки (gen/pipeline.py)
      SWAP_ENFORCE_FINAL: "0"          # дополнительный финальный своп (gen/pipeline.py)
      INSIGHTFACE_DET_SIZE: "896"      # размер детектора лиц (gen/services/face_swapper.py)
      INSIGHTFACE_DET_THRESH: "0.25"   # порог детектора лиц (face_swapper.py)
      SWAP_EAR_EXPAND_PX: "36"         # баз. расширение по X для ушей (face_swapper.py: _extended_mask)
      SWAP_EAR_MULT: "1.8"             # множитель расширения ушей (face_swapper.py)
      SWAP_EAR_ITERS: "3"              # кол-во дилатаций ушей (face_swapper.py)
      SWAP_EAR_RECT_W: "24"            # «карманы» по бокам bbox (face_swapper.py)
      SWAP_HAIR_EXPAND_PX: "20"        # расширение вверх (волосы) (face_swapper.py)
      SWAP_CHIN_CUT_PX: "8"            # обрез снизу по подбородку (face_swapper.py)
      POISSON_FACE: "1"                # узкий Poisson по границе (face_swapper.py)
      SWAP_POISSON_FULL: "1"           # полноразмерный Poisson по ext_mask (face_swapper.py)
      SWAP_SHARP_GAIN: "0.22"          # лёгкая резкость после свопа (face_swapper.py)
      FACE_MODEL_PATH: "/models/inswapper_128.onnx" # путь к ONNX‑модели inswapper (face_swapper.py)
      DISABLE_HANDS: "0"               # выключить распознавание рук (gen/utils/utils.py)
      DISABLE_FACEMESH: "0"            # выключить FaceMesh (face_swapper.py)
      SWAP_KEEP_EARS: "1"              # оставить уши таргета (естественнее на большинстве кадров)
      SWAP_CORE_SHRINK_PX: "6"         # сужение «ядра» при KEEP_EARS (face_swapper.py)
      HAND_SKIN_UNION: "1"             # объединять маску рук с skin‑mask (gen/utils/utils.py: hand_mask_bgr)
      HAND_DILATE_PX: "14"              # расширить маску руки (hand_mask_bgr)
      HAND_ERODE_PX: "2"                # затем чуть усадить (hand_mask_bgr)
      CONTACT_FEATHER: "2.2"            # перо контактной тени (gen/pipeline.py)
      CONTACT_SHADE: "0.12"             # сила контактной тени (gen/pipeline.py)
      # волосы источника (опционально)
      HAIR_FROM_SRC: "0"                # подмешивать волосы источника (face_swapper.py)
      SWAP_DETAIL_GAIN: "0.18"          # реинжект высоких частот (face_swapper.py)
      SWAP_DETAIL_SIGMA: "1.0"          # размер «пор» для деталей (face_swapper.py)
      SWAP_FORCE_EARS: "0"              # не принуждать Poisson ушей при KEEP_EARS=1
      SWAP_EAR_HARD: "0"                # не заменяем уши (оставляем таргет)
      SWAP_EAR_FEATHER: "6"             # перо для ушей (face_swapper.py)
      SWAP_EAR_CLONE: "0"               # локальный Poisson по каждой ушной компоненте (face_swapper.py)
      SWAP_EAR_CLONE_MODE: "normal"     # normal|mixed (face_swapper.py)
      SWAP_EAR_ERODE: "2"               # усадка ушной маски перед clone (face_swapper.py)
      SWAP_EAR_MIN_AREA: "300"          # мин. площадь компоненты уха (face_swapper.py)
      HAIR_ALPHA: "0.3"                 # сила волос источника (face_swapper.py)
      SWAP_FORCE_FULL: "0"              # вернуть сырой swap без маски (face_swapper.py)
      SWAP_BBOX_OVAL_PAD_PCT: "0.12"    # поля овала при bbox‑fallback маски (face_swapper.py)
      # Тон‑матч и сглаживание артефактов лица
      SWAP_TONEMATCH_GAIN: "0.50"       # 0.0=rough, 1.0=matched (face_swapper.py)
      SWAP_MOUTH_SOFTEN: "1"            # смягчить зону губ (face_swapper.py)
      SWAP_MOUTH_BAND_PX: "12"          # ширина полосы для губ (px) (face_swapper.py)
      SWAP_MOUTH_BLEND: "0.50"          # сила подмешивания таргета в зоне губ (face_swapper.py)
      # Dehalo по краю уха (актуально если переносим уши источника)
      SWAP_EAR_DEHALO: "1"              # включить dehalo ушей (face_swapper.py)
      SWAP_EAR_DEHALO_GAIN: "0.25"      # сила притяжения края к таргету (face_swapper.py)
      SWAP_EAR_DEHALO_SIGMA: "1.6"      # перо dehalo (face_swapper.py)

      # Отладка
      SAVE_DEBUG: "1"                   # сохранять debug_* в /tmp (сервисы и API)
      SKIP_INPAINT: "0"                 # пропустить SD‑inpaint (gen/pipeline.py)
      FALLBACK_INPAINT: "0"              # принудит. OpenCV‑inpaint (gen/pipeline.py)
      OUTPUT_FORMAT: "png"               # формат ответа (api/server), пока png
      USE_CPU: "0"                       # CPU режим для torch/onnx (face_swapper.py/inpainter.py)

      SWAP_SELECT: "center"       # варианты: center | largest | index
      SWAP_INDEX: "0"             # используется, если SWAP_SELECT=index

      # усиление заметности свопа
      SWAP_CORE_GAIN: "1.5"            # усиление «ядра» (face_swapper.py)
      SWAP_HAIR_ALPHA: "1"             # сила волос (face_swapper.py)
      SWAP_CORE_DILATE: "8"            # ширина «ядра» (face_swapper.py)
      SWAP_ENFORCE_CORE: "1"           # закрепить ядро после Poisson (face_swapper.py)
      SWAP_CORE_FEATHER: "2.2"         # перо при закреплении ядра (face_swapper.py)

      # отладка
      SWAP_DEBUG: "1"
      DEFAULT_PROMPT: >-
        photorealistic selfie; person holding a postcard; keep postcard unchanged;
        natural skin texture; soft contact shadows; realistic fingers, no blur
      NEG_PROMPT: >-
        altered postcard, changed text, hdr halos, glow edges, extra fingers,
        deformed hands, warped text, logo distortion, oversharpen, blur, artifacts

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

    volumes:
      - ./gen/models:/models:ro
      - hf_cache:/root/.cache/huggingface
      - /tmp:/tmp

    restart: unless-stopped

volumes:
  hf_cache:
