# Compose V2 (без поля version)
services:
  gen:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: postcard-selfie-gen:gpu
    ports:
      - "8081:8081"
    # требуется Docker с nvidia-container-toolkit
    deploy: {}
    gpus: all
    environment:
      PYTHONUNBUFFERED: "1"

      # Torch/threads
      TORCH_THREADS: "4"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      TOKENIZERS_PARALLELISM: "false"
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:128"
      TRANSFORMERS_NO_TORCHVISION: "1"
      HF_HUB_ENABLE_HF_TRANSFER: "0"

      # SD / Inpaint
      INPAINT_REPO: "runwayml/stable-diffusion-inpainting"
      TORCH_dtype: "fp16"
      MAX_SIDE: "1600"
      STEPS: "22"
      GUIDANCE: "4.0"
      STRENGTH: "0.46"

      # Патч-инпейнт
      INPAINT_LONG: "1400"
      INPAINT_PAD_PCT: "0.08"
      MASK_GROW: "4"

      # Кромка/контакт
      RING_IN_PCT: "0.0035"
      RING_OUT_PCT: "0.010"
      EDGE_SNAP_ITERS: "2"
      RIM_SHADE: "0.045"
      SEAMLESS_EDGE: "1"

      # Детали кожи/зерно
      FINGER_DETAIL_SIGMA: "1.1"
      FINGER_DETAIL_GAIN: "0.38"
      GRAIN_STRENGTH: "0.010"

      # Эффект страницы
      PAGE_EFFECT: "1"
      PAGE_SIDE: "right"
      PAGE_INNER_PX: "14"
      PAGE_SHADE: "0.05"
      PAGE_STRIPES: "1"

      # Faceswap
      DISABLE_FACE_SWAP: "0"
      SWAP_MODE: "before"
      INSIGHTFACE_DET_SIZE: "800"
      FACE_MODEL_PATH: "/models/inswapper_128.onnx"
      DISABLE_HANDS: "0"
      DISABLE_FACEMESH: "0"

      # Отладка
      SAVE_DEBUG: "0"
      SKIP_INPAINT: "0"
      FALLBACK_INPAINT: "0"
      OUTPUT_FORMAT: "png"
      USE_CPU: "0"

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

    volumes:
      - ./gen/models:/models:ro
      - hf_cache:/root/.cache/huggingface
      - /tmp:/tmp

    restart: unless-stopped

volumes:
  hf_cache:
