services:
  gen:
    build:
      context: ./gen
      dockerfile: Dockerfile.gpu
    image: selfie-postcard-gen-gpu:latest
    ports:
      - "8081:8081"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
    environment:
      # GPU
      USE_CPU: "0"
      TORCH_dtype: "fp16"

      # Hugging Face — включить быстрый загрузчик можно, если lib hf_transfer установлен
      HF_HUB_ENABLE_HF_TRANSFER: "0"
      # HF_HUB_TOKEN: "${HF_HUB_TOKEN}"     # <- если используешь приватные репозитории, добавь в .env

      # Параметры пайплайна
      INPAINT_REPO: "runwayml/stable-diffusion-inpainting"
      MAX_SIDE: "1280"
      STEPS: "18"
      GUIDANCE: "5.0"
      STRENGTH: "0.5"
      OUTPUT_FORMAT: "png"

      # Переключатели
      SKIP_INPAINT: "0"
      DISABLE_HANDS: "0"
      DISABLE_FACEMESH: "0"

      # FaceSwap
      SWAP_MODE: "before"
      DISABLE_FACE_SWAP: "0"
      INSIGHTFACE_DET_SIZE: "640"
      FACE_MODEL_PATH: "/models/inswapper_128.onnx"

      # Треды
      TORCH_THREADS: "8"
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"

      # Промпты (при желании)
      DEFAULT_PROMPT: "photorealistic selfie; person holding a postcard; keep postcard exactly unchanged; soft contact shadows; realistic fingers"
      NEG_PROMPT: "altered postcard, changed text, boosted contrast, glow edges, hdr halos, deformed hands, extra fingers, warped text, logo distortion, blur, artifacts"

    volumes:
      - ./gen/models:/models:ro
      - hf_cache:/root/.cache/huggingface
      - /tmp:/tmp
    shm_size: "2g"
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s

volumes:
  hf_cache:
